include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - require_trailing_commas
#    avoid_print: true
#    avoid_empty_else: true
#    curly_braces_in_flow_control_structures: true
#    unawaited_futures: false
#    omit_local_variable_types: false
#    prefer_final_fields: true
#    non_constant_identifier_names: true
#    avoid_dynamic_calls: true
#    noop_primitive_operations: true
