name: wifi_List_Test_Task
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.12

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.5
  injectable: ^2.4.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  bloc: ^8.1.3

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 2.4.9
  injectable_generator: ^2.6.1
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/


